apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: configmap-cleaner
  name: configmap-cleaner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-cleaner
  namespace: system
  labels:
    app: configmap-cleaner
spec:
  selector:
    matchLabels:
      app: configmap-cleaner
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: configmap-cleaner
    spec:
      containers:
      - command:
        - /manager
        args:
        image: manager
        imagePullPolicy: Always
        name: manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
