apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: configmap-cleaner
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: configmap-cleaner
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: configmap-cleaner
