apiVersion: v1
kind: Service
metadata:
  labels:
    app: configmap-cleaner
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: configmap-cleaner
