apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager
  namespace: configmap-cleaner
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
